<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SssContributionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sss_contribution')->delete();
        
        \DB::table('sss_contribution')->insert(array (
            0 => 
            array (
                'id' => 2,
                'from_rate' => '0.00',
                'to_rate' => '3250',
                'msc_rss_ec' => '3000',
                'msc_mpf' => '0',
                'msc_total' => '3000',
                'ac_rss_er' => '255',
                'ac_rss_ee' => '135',
                'ac_rss_total' => '390',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '265',
                'ac_ee_total' => '135',
                'ac_total_total' => '400',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'from_rate' => '3250.00',
                'to_rate' => '3749.99',
                'msc_rss_ec' => '3500',
                'msc_mpf' => '0',
                'msc_total' => '3500',
                'ac_rss_er' => '297.5',
                'ac_rss_ee' => '157.5',
                'ac_rss_total' => '455',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '307.5',
                'ac_ee_total' => '157.5',
                'ac_total_total' => '465',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'from_rate' => '3750.00',
                'to_rate' => '4249.99',
                'msc_rss_ec' => '4000',
                'msc_mpf' => '0',
                'msc_total' => '4000',
                'ac_rss_er' => '340',
                'ac_rss_ee' => '180',
                'ac_rss_total' => '520',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '350',
                'ac_ee_total' => '180',
                'ac_total_total' => '530',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'from_rate' => '4250.00',
                'to_rate' => '4749.99',
                'msc_rss_ec' => '4500',
                'msc_mpf' => '0',
                'msc_total' => '4500',
                'ac_rss_er' => '382.5',
                'ac_rss_ee' => '202.5',
                'ac_rss_total' => '585',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '392.5',
                'ac_ee_total' => '202.5',
                'ac_total_total' => '595',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'from_rate' => '4750.00',
                'to_rate' => '5249.99',
                'msc_rss_ec' => '5000',
                'msc_mpf' => '0',
                'msc_total' => '5000',
                'ac_rss_er' => '425',
                'ac_rss_ee' => '225',
                'ac_rss_total' => '650',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '435',
                'ac_ee_total' => '225',
                'ac_total_total' => '660',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'from_rate' => '5250.00',
                'to_rate' => '5749.99',
                'msc_rss_ec' => '5500',
                'msc_mpf' => '0',
                'msc_total' => '5500',
                'ac_rss_er' => '467.5',
                'ac_rss_ee' => '247.5',
                'ac_rss_total' => '715',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '477.5',
                'ac_ee_total' => '247.5',
                'ac_total_total' => '725',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'from_rate' => '5750.00',
                'to_rate' => '6249.99',
                'msc_rss_ec' => '6000',
                'msc_mpf' => '0',
                'msc_total' => '6000',
                'ac_rss_er' => '510',
                'ac_rss_ee' => '270',
                'ac_rss_total' => '780',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '520',
                'ac_ee_total' => '270',
                'ac_total_total' => '790',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'from_rate' => '6250.00',
                'to_rate' => '6749.99',
                'msc_rss_ec' => '6500',
                'msc_mpf' => '0',
                'msc_total' => '6500',
                'ac_rss_er' => '552.5',
                'ac_rss_ee' => '292.5',
                'ac_rss_total' => '845',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '562.5',
                'ac_ee_total' => '292.5',
                'ac_total_total' => '855',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'from_rate' => '6750.00',
                'to_rate' => '7249.99',
                'msc_rss_ec' => '7000',
                'msc_mpf' => '0',
                'msc_total' => '7000',
                'ac_rss_er' => '595',
                'ac_rss_ee' => '315',
                'ac_rss_total' => '910',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '605',
                'ac_ee_total' => '315',
                'ac_total_total' => '920',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'from_rate' => '7250.00',
                'to_rate' => '7749.99',
                'msc_rss_ec' => '7500',
                'msc_mpf' => '0',
                'msc_total' => '7500',
                'ac_rss_er' => '637.5',
                'ac_rss_ee' => '337.5',
                'ac_rss_total' => '975',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '647.5',
                'ac_ee_total' => '337.5',
                'ac_total_total' => '985',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'from_rate' => '7750.00',
                'to_rate' => '8249.99',
                'msc_rss_ec' => '8000',
                'msc_mpf' => '0',
                'msc_total' => '8000',
                'ac_rss_er' => '680',
                'ac_rss_ee' => '360',
                'ac_rss_total' => '1040',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '690',
                'ac_ee_total' => '360',
                'ac_total_total' => '1050',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'from_rate' => '8250.00',
                'to_rate' => '8749.99',
                'msc_rss_ec' => '8500',
                'msc_mpf' => '0',
                'msc_total' => '8500',
                'ac_rss_er' => '722.5',
                'ac_rss_ee' => '382.5',
                'ac_rss_total' => '1105',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '732.5',
                'ac_ee_total' => '382.5',
                'ac_total_total' => '1115',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'from_rate' => '8750.00',
                'to_rate' => '9249.99',
                'msc_rss_ec' => '9000',
                'msc_mpf' => '0',
                'msc_total' => '9000',
                'ac_rss_er' => '765',
                'ac_rss_ee' => '405',
                'ac_rss_total' => '1170',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '775',
                'ac_ee_total' => '405',
                'ac_total_total' => '1180',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'from_rate' => '9250.00',
                'to_rate' => '9749.99',
                'msc_rss_ec' => '9500',
                'msc_mpf' => '0',
                'msc_total' => '9500',
                'ac_rss_er' => '807.5',
                'ac_rss_ee' => '427.5',
                'ac_rss_total' => '1235',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '817.5',
                'ac_ee_total' => '427.5',
                'ac_total_total' => '1245',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'from_rate' => '9750.00',
                'to_rate' => '10249.99',
                'msc_rss_ec' => '10000',
                'msc_mpf' => '0',
                'msc_total' => '10000',
                'ac_rss_er' => '850',
                'ac_rss_ee' => '450',
                'ac_rss_total' => '1300',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '860',
                'ac_ee_total' => '450',
                'ac_total_total' => '1310',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'from_rate' => '10250.00',
                'to_rate' => '10749.99',
                'msc_rss_ec' => '10500',
                'msc_mpf' => '0',
                'msc_total' => '10500',
                'ac_rss_er' => '892.5',
                'ac_rss_ee' => '472.5',
                'ac_rss_total' => '1365',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '902.5',
                'ac_ee_total' => '472.5',
                'ac_total_total' => '1375',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'from_rate' => '10750.00',
                'to_rate' => '11249.99',
                'msc_rss_ec' => '11000',
                'msc_mpf' => '0',
                'msc_total' => '11000',
                'ac_rss_er' => '935',
                'ac_rss_ee' => '495',
                'ac_rss_total' => '1430',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '945',
                'ac_ee_total' => '495',
                'ac_total_total' => '1440',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'from_rate' => '11250.00',
                'to_rate' => '11749.99',
                'msc_rss_ec' => '11500',
                'msc_mpf' => '0',
                'msc_total' => '11500',
                'ac_rss_er' => '977.5',
                'ac_rss_ee' => '517.5',
                'ac_rss_total' => '1495',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '987.5',
                'ac_ee_total' => '517.5',
                'ac_total_total' => '1505',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'from_rate' => '11750.00',
                'to_rate' => '12249.99',
                'msc_rss_ec' => '12000',
                'msc_mpf' => '0',
                'msc_total' => '12000',
                'ac_rss_er' => '1020',
                'ac_rss_ee' => '540',
                'ac_rss_total' => '1560',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1030',
                'ac_ee_total' => '540',
                'ac_total_total' => '1570',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'from_rate' => '12250.00',
                'to_rate' => '12749.99',
                'msc_rss_ec' => '12500',
                'msc_mpf' => '0',
                'msc_total' => '12500',
                'ac_rss_er' => '1062.5',
                'ac_rss_ee' => '562.5',
                'ac_rss_total' => '1625',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1072.5',
                'ac_ee_total' => '562.5',
                'ac_total_total' => '1635',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'from_rate' => '12750.00',
                'to_rate' => '13249.99',
                'msc_rss_ec' => '13000',
                'msc_mpf' => '0',
                'msc_total' => '13000',
                'ac_rss_er' => '1105',
                'ac_rss_ee' => '585',
                'ac_rss_total' => '1690',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1115',
                'ac_ee_total' => '585',
                'ac_total_total' => '1700',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'from_rate' => '13250.00',
                'to_rate' => '13749.99',
                'msc_rss_ec' => '13500',
                'msc_mpf' => '0',
                'msc_total' => '13500',
                'ac_rss_er' => '1147.5',
                'ac_rss_ee' => '607.5',
                'ac_rss_total' => '1755',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1157.5',
                'ac_ee_total' => '607.5',
                'ac_total_total' => '1765',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'from_rate' => '13750.00',
                'to_rate' => '14249.99',
                'msc_rss_ec' => '14000',
                'msc_mpf' => '0',
                'msc_total' => '14000',
                'ac_rss_er' => '1190',
                'ac_rss_ee' => '630',
                'ac_rss_total' => '1820',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1200',
                'ac_ee_total' => '630',
                'ac_total_total' => '1830',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'from_rate' => '14250.00',
                'to_rate' => '14749.99',
                'msc_rss_ec' => '14500',
                'msc_mpf' => '0',
                'msc_total' => '14500',
                'ac_rss_er' => '1232.5',
                'ac_rss_ee' => '652.5',
                'ac_rss_total' => '1885',
                'ac_ec_er' => '10',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '10',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1242.5',
                'ac_ee_total' => '652.5',
                'ac_total_total' => '1895',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'from_rate' => '14750.00',
                'to_rate' => '15249.99',
                'msc_rss_ec' => '15000',
                'msc_mpf' => '0',
                'msc_total' => '15000',
                'ac_rss_er' => '1275',
                'ac_rss_ee' => '675',
                'ac_rss_total' => '1950',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1305',
                'ac_ee_total' => '675',
                'ac_total_total' => '1980',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'from_rate' => '15250.00',
                'to_rate' => '15749.99',
                'msc_rss_ec' => '15500',
                'msc_mpf' => '0',
                'msc_total' => '15500',
                'ac_rss_er' => '1317.5',
                'ac_rss_ee' => '697.5',
                'ac_rss_total' => '2015',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1347.5',
                'ac_ee_total' => '697.5',
                'ac_total_total' => '2045',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'from_rate' => '15750.00',
                'to_rate' => '16249.99',
                'msc_rss_ec' => '16000',
                'msc_mpf' => '0',
                'msc_total' => '16000',
                'ac_rss_er' => '1360',
                'ac_rss_ee' => '720',
                'ac_rss_total' => '2080',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1390',
                'ac_ee_total' => '720',
                'ac_total_total' => '2110',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'from_rate' => '16250.00',
                'to_rate' => '16749.99',
                'msc_rss_ec' => '16500',
                'msc_mpf' => '0',
                'msc_total' => '16500',
                'ac_rss_er' => '1402.5',
                'ac_rss_ee' => '742.5',
                'ac_rss_total' => '2145',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1432.5',
                'ac_ee_total' => '742.5',
                'ac_total_total' => '2175',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'from_rate' => '16750.00',
                'to_rate' => '17249.99',
                'msc_rss_ec' => '17000',
                'msc_mpf' => '0',
                'msc_total' => '17000',
                'ac_rss_er' => '1445',
                'ac_rss_ee' => '765',
                'ac_rss_total' => '2210',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1475',
                'ac_ee_total' => '765',
                'ac_total_total' => '2240',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'from_rate' => '17250.00',
                'to_rate' => '17749.99',
                'msc_rss_ec' => '17500',
                'msc_mpf' => '0',
                'msc_total' => '17500',
                'ac_rss_er' => '1487.5',
                'ac_rss_ee' => '787.5',
                'ac_rss_total' => '2275',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1517.5',
                'ac_ee_total' => '787.5',
                'ac_total_total' => '2305',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'from_rate' => '17750.00',
                'to_rate' => '18249.99',
                'msc_rss_ec' => '18000',
                'msc_mpf' => '0',
                'msc_total' => '18000',
                'ac_rss_er' => '1530',
                'ac_rss_ee' => '810',
                'ac_rss_total' => '2340',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1560',
                'ac_ee_total' => '810',
                'ac_total_total' => '2370',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'from_rate' => '18250.00',
                'to_rate' => '18749.99',
                'msc_rss_ec' => '18500',
                'msc_mpf' => '0',
                'msc_total' => '18500',
                'ac_rss_er' => '1572.5',
                'ac_rss_ee' => '832.5',
                'ac_rss_total' => '2405',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1602.5',
                'ac_ee_total' => '832.5',
                'ac_total_total' => '2435',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'from_rate' => '18750.00',
                'to_rate' => '19249.99',
                'msc_rss_ec' => '19000',
                'msc_mpf' => '0',
                'msc_total' => '19000',
                'ac_rss_er' => '1615',
                'ac_rss_ee' => '855',
                'ac_rss_total' => '2470',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1645',
                'ac_ee_total' => '855',
                'ac_total_total' => '2500',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'from_rate' => '19250.00',
                'to_rate' => '19749.99',
                'msc_rss_ec' => '19500',
                'msc_mpf' => '0',
                'msc_total' => '19500',
                'ac_rss_er' => '1657.5',
                'ac_rss_ee' => '877.5',
                'ac_rss_total' => '2535',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1687.5',
                'ac_ee_total' => '877.5',
                'ac_total_total' => '2565',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'from_rate' => '19750.00',
                'to_rate' => '20249.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '0',
                'msc_total' => '20000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '0',
                'ac_mpf_ee' => '0',
                'ac_mpf_total' => '0',
                'ac_er_total' => '1730',
                'ac_ee_total' => '900',
                'ac_total_total' => '2630',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'from_rate' => '20250.00',
                'to_rate' => '20749.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '500',
                'msc_total' => '20500',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '42.5',
                'ac_mpf_ee' => '22.5',
                'ac_mpf_total' => '65',
                'ac_er_total' => '1772.5',
                'ac_ee_total' => '922.5',
                'ac_total_total' => '2695',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'from_rate' => '20750.00',
                'to_rate' => '21249.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '1000',
                'msc_total' => '21000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '85',
                'ac_mpf_ee' => '45',
                'ac_mpf_total' => '130',
                'ac_er_total' => '1815',
                'ac_ee_total' => '945',
                'ac_total_total' => '2760',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'from_rate' => '21250.00',
                'to_rate' => '21749.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '1500',
                'msc_total' => '21500',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '127.5',
                'ac_mpf_ee' => '67.5',
                'ac_mpf_total' => '195',
                'ac_er_total' => '1857.5',
                'ac_ee_total' => '967.5',
                'ac_total_total' => '2825',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'from_rate' => '21750.00',
                'to_rate' => '22249.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '2000',
                'msc_total' => '22000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '170',
                'ac_mpf_ee' => '90',
                'ac_mpf_total' => '260',
                'ac_er_total' => '1900',
                'ac_ee_total' => '990',
                'ac_total_total' => '2890',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'from_rate' => '22250.00',
                'to_rate' => '22749.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '2500',
                'msc_total' => '22500',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '212.5',
                'ac_mpf_ee' => '112.5',
                'ac_mpf_total' => '325',
                'ac_er_total' => '1942.5',
                'ac_ee_total' => '1012.5',
                'ac_total_total' => '2955',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'from_rate' => '22750.00',
                'to_rate' => '23249.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '3000',
                'msc_total' => '23000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '255',
                'ac_mpf_ee' => '135',
                'ac_mpf_total' => '390',
                'ac_er_total' => '1985',
                'ac_ee_total' => '1035',
                'ac_total_total' => '3020',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'from_rate' => '23250.00',
                'to_rate' => '23749.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '3500',
                'msc_total' => '23500',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '297.5',
                'ac_mpf_ee' => '157.5',
                'ac_mpf_total' => '455',
                'ac_er_total' => '2027.5',
                'ac_ee_total' => '1057.5',
                'ac_total_total' => '3085',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'from_rate' => '23750.00',
                'to_rate' => '24249.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '4000',
                'msc_total' => '24000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '340',
                'ac_mpf_ee' => '180',
                'ac_mpf_total' => '520',
                'ac_er_total' => '2070',
                'ac_ee_total' => '1080',
                'ac_total_total' => '3150',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'from_rate' => '24250.00',
                'to_rate' => '24749.99',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '4500',
                'msc_total' => '24500',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '382.5',
                'ac_mpf_ee' => '202.5',
                'ac_mpf_total' => '585',
                'ac_er_total' => '2112.5',
                'ac_ee_total' => '1102.5',
                'ac_total_total' => '3215',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'from_rate' => '24750.00',
                'to_rate' => '999999',
                'msc_rss_ec' => '20000',
                'msc_mpf' => '5000',
                'msc_total' => '25000',
                'ac_rss_er' => '1700',
                'ac_rss_ee' => '900',
                'ac_rss_total' => '2600',
                'ac_ec_er' => '30',
                'ac_ec_ee' => '0',
                'ac_ec_total' => '30',
                'ac_mpf_er' => '425',
                'ac_mpf_ee' => '225',
                'ac_mpf_total' => '650',
                'ac_er_total' => '2155',
                'ac_ee_total' => '1125',
                'ac_total_total' => '3280',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}