<?php

use Illuminate\Database\Seeder;

class TimetableTaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       /* DB::table('timetable_tasks')->truncate();

		DB::statement("INSERT INTO timetable_tasks (id,timetable_id,task) VALUES
			(1, 1,'MINUTES'),
			(2, 2,'P.O / SIGNED QUOTATION'),
			(3, 2,'CONTRACT'),
			(4, 2,'C.O.R'),
			(5, 2,'SALES ORDER'),
			(6, 2,'BILL OF MATERIALS'),
			(7, 2,'SITE PICTURES / FLOOR PLAN / HARDWARE LAY-OUT'),
			(8, 2,'PROCESS FLOW / SYSTEM LAY-OUT / PRESENTATION'),
			(9, 2,'PROJECT KICK OFF'),
			(10, 3,'SURETY / CARI / PERFORMANCE / GUARANTEE BOND'),
			(11, 3,'COLLECTION OF DOWNPAYMENT'),
			(12, 3,'COLLECTION OF PROGRESS BILLING'),
			(13, 3,'COLLECTION OF FULL PAYMENT'),						
			(14, 3,'BILLING / SI / DR / MP PREPARATION'),
			(15, 3,'ISSUANCE OF WARRANTY CERTIFICATE'),		
			(16, 4,'CHECKING OF STOCKS AVAILABILITY'),
			(17, 4,'P.O TO SUPPLIER IF WITHOUT STOCK'),
			(18, 4,'OFFER ALTERNATIVE EQUIPMENT IF WITHOUT STOCK'),
			(19, 4,'STOCK ORDERING / STOCK VERIFICATIONVAND RELEASING'),
			(20, 5,'SECURE C.O.R., SUBMIT BIR FORM'),
			(21, 5,'BIR APPLICATION / PROCESSING ONLINE'),
			(22, 6,'SURVEY SITE LAYOUT FOR CABLING / LAN'),
			(23, 6,'IDENTIFY MATERIALS AND MANPOWER NEEDED'),
			(24, 6,'NETWORK CONFIGURATION AND CABLING'),
			(25, 6,'NETWORK LAY-OUTING / TERMINATION'),
			(26, 6,'CREATION OF FINAL LAYOUT / FLOOR PLAN FOR APPROVAL'),
			(27, 6,'CREATE SAMPLE OR PROTOTYPE FOR APPROVAL'),
			(28, 6,'SITE SURVEY / MARKINGS / LAYOUT'),
			(29, 6,'CIVIL WORKS AND CONSTRUCTION PROPER'),			
			(30, 7,'CREATION OF SRS BASED ON WISH LIST'),
			(31, 7,'REVIEW AND APPROVAL OF SRS'),
			(32, 7,'PROGRAM DOCUMENTATION & USER MANUAL'),
			(33, 7,'PROGRAM DESIGN / CODING / DEVELOPEMENT'),
			(34, 7,'SOFTWARE TESTING AND DEBUGGING'),
			(35, 8,'SITE INSPECTION / MALL ADMIN REQUESTS'),
			(36, 8,'CABLING TERMINATION AND HOOK UP CONNECTION'),
			(37, 8,'MALL SENDING TESTING AND ACCEPTANCE'),
			(38, 9,'DELIVERY / PICK-UP / SHIPPING GOODS'),			
			(39, 10,'ASSEMBLY OF TERMINAL & OS INSTALLATION'),
			(40, 10,'EQUIPMENT TESTING / SERIAL NO'),
			(41, 10,'HARWARE SIMULATION AND TESTING'),
			(42, 10,'EQUIPMENT WARRANTY STICKER'),
			(43, 10,'PRESENTATION OF ACTUAL HARDWARE'),
			(44, 10,'BASIC TROUBLESHOOTING / START END DAY REVIEW'),
			(45, 10,'CHECKING OTHER ISSUES WITH THE CLIENT REGARDING PROJECT DELIVERABLES'),
			(46, 10,'TURN OVER OF ALL DOCS AND REPORTS FOR SIGN OFF'),			
			(47, 11,'SOFTWARE INSTALLATION / COMPATABILITY TESTING'),
			(48, 11,'SOFTWARE SIMULATION'),
			(49, 11,'CONNECTIVITY SETTINGS OF ALL EQUIPMENTS'),
			(50, 11,'PRESENTATION OF ACTUAL SOFTWARE'),
			(51, 11,'ON SITE SOFTWARE SIMULATION'),
			(52, 11,'CONNECTIVITY AND CONFIGURATION'),
			(53, 11,'ENCODING / CONFIGURATION  OF BIR PERMIT INFO'),
			(54, 11,'DATA MIGRATION / GETTING MASTERFILE'),
			(55, 11,'LIVE RUN MONITORING'),			
			(56, 11,'LISTING OF CONCERNS AND REPORTING'),
			(57, 11,'TURN OVER OF ALL DOCS AND REPORTS FOR SIGN OFF'),
			(58, 11,'SIGNING OF COC WITH CLIENT')");*/
    }
}
